name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all available fields!
        All additional contect is not required and you can put it in last field.
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: example. When I click on button, modal didn't show up.
    validations:
      required: true
  - type: textarea
    id: str
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      placeholder: example. Click on ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe expected behavior
      placeholder: example. When I click on button, modal shows up.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Describe additional context
    validations:
      required: false
