name: Epic User Story
description: Epic for other User stories
title: "[Epic Story]: "
labels: ["User Story", "Epic"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all available fields!
  - type: textarea
    id: story-description
    attributes:
      label: General description
      description: Descripbe the general story
      placeholder: example. As a user, I want to do something...
      value: "As a user, I want to"
    validations:
      required: true
  - type: textarea
    id: related-stories
    attributes:
      label: Related stories
      description: List all related stories. After you can create issues from list items.
      value: |
        - [ ] Some feature related to this story
        - [ ] Additional related story
        - [ ] ...
        ...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Describe additional context
    validations:
      required: false
