name: Feature request
description: Feature request description template
title: "[Feature]: "
labels: ["Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please put as much description as you can. This will help to understand what feature you want to implement.
  - type: textarea
    id: feature-description
    attributes:
      label: General description
      description: Descripbe all feature details here
      placeholder: example. Button should be of color blue and border should be 1px solid darkgray.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Describe additional context
    validations:
      required: false
