name: User Story
description: User story template
title: "[Story]: "
labels: ["User Story"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill inall available fields!
  - type: textarea
    id: story-description
    attributes:
      label: Story description
      description: Describe the user story
      placeholder: As a user, I want to do something...
      value: "As a user, I want to"
    validations:
      required: true
  - type: textarea
    id: pre-conditions
    attributes:
      label: Story pre-conditions
      description: Describe pre-conditions
      placeholder: Local storage is empty
      value: "Clear local storage"
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Describe acceptance criteria
      placeholder: Label has text and is visible
      value: "List of acceptance criterias"
    validations:
      required: false
