name: User Story
description: User story description template
title: "[Story]: "
labels: ["User Story"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all available fields!
  - type: textarea
    id: story-description
    attributes:
      label: Description
      description: Describe the user story
      placeholder: example. As a user, I want to do something...
      value: "As a user, I want to"
    validations:
      required: true
  - type: textarea
    id: pre-conditions
    attributes:
      label: Pre-conditions
      description: Describe pre-conditions
      placeholder: example. 1. Local storage is empty
      value: |
        - Local storage is empty
        - Browser window width is more than 500px 
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Describe acceptance criteria
      value: |
        #### Scenario 1
        1. Header is shown on application load
        2. Logo is shown in top left corner
    validations:
      required: true
