replicaCount: 1

image:
  repository: "ghcr.io/nedilko/weekends"
  tag: ""
  pullPolicy: IfNotPresent

# imagePullSecrets:
#   - name: gitlab-registry

nameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: "dev.weekends.love.nac.in.ua"
  tls:
    secretName: ""
    hosts: "dev.weekends.love.nac.in.ua"

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}