name: test CI

on:
  push:
    branches: 
      - main
      - "feature/*"
      - "bug/*"
      - "bugfix/*"
      - "fix/*"
      - "hotfix/*"
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use node v14  
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
